### PR TITLE
Final Changes to Library Project

### PR DESCRIPTION
**Pull request by evaveskova**
In this, we:

- Created the skeleton of the page with HTML and CSS.
- Created a library function using JavaScript.
- Added the ability for users to add new books to the library in the browser.
- Added a method to delete book entries with a button.
- Created a method to set the status of a book as being either 'read' or 'not read'.

### CODE REVIEW

**Review by bellom — CHANGES_REQUESTED** [review]
## Hi Team  :clap: 
### Awesome job so far!! :+1: 
#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1:, just one issue left to work on............ :slightly_smiling_face: 

`New Book` button ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/library/new_book_button_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/library))

We already discuss this on slack, implement this feature and you're good to go 👍 

**Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....**

Best,

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

**Comment by evaveskova** [comment]
Requested changes have been made.

**Comment by bellom** [comment]
Kindly reply on slack, let fix the issues and move on.
The `new book button` feature you added seems to have little bug.

**Comment by KerronKing** [comment]
Thanks for pointing that out. We fixed the bug and it works fine now.

**Review by bellom — APPROVED** [review]
## Hi Team :clap: 

**Great work making all the necessary corrections from the previous review.**

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit project completion form.
Goodluck in the next project :slightly_smiling_face:_ 

Best,

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

**Pull request merged**
